### PR TITLE
Add the ability to specify numberOfMonths to show in the picker

### PR DESCRIPTION
**Pull request by ghost**
Added the ability to specify number of months to show in the picker. It defaults to 3 if nothing specified.

### CODE REVIEW

**Comment by thetutlage** [comment]
Can you please remove `.idea/workspace.xml` file?

**Comment by AngularDevMrs** [comment]
Removed it. Thanks.

**Comment by thetutlage** [comment]
Thanks for the PR :)

**Comment by AngularDevMrs** [comment]
You are welcome :+1: Thanks for supplying this datepicker. Very helpful.

**Pull request merged**
